# Generated by Django 4.2 on 2025-05-23 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do Humor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mood_images/', verbose_name='Imagem do Humor')),
            ],
            options={
                'verbose_name': 'Humor Padrão',
                'verbose_name_plural': 'Humores Padrão',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Adicional')),
                ('entry_date', models.DateField(verbose_name='Data da Entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('mood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mood_api.defaultmood', verbose_name='Humor Selecionado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Entrada de Humor',
                'verbose_name_plural': 'Entradas de Humor',
                'ordering': ['-entry_date', '-created_at'],
                'unique_together': {('user', 'entry_date')},
            },
        ),
    ]
